<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticles() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('a')->from('AppBundle:Article', 'a')->orderBy('a.id', 'DESC');

        return $qb->getQuery()->getArrayResult();
    }

    public function getArticleById($id) {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('a')->from('AppBundle:Article', 'a')->where('a.id = :id');
        $qb->setParameters(['id'=>$id]);

        return $qb->getQuery()->getResult()[0];
    }
}
